### ISSUE TITLE
Code about simulating events on FlyingChairs2

### ISSUE THREAD

**Issue by wwsource** [danqu130/DCEIFlow#1]
Nice work!
Can you release the codes about simulating events on FlyingChairs2 or release the event datasets for easy use.

**Comment by danqu130** [comment]
In order to avoid unnecessary misunderstanding of rights, we do not plan to provide simulated event data. If anyone needs the code of event simulation, please leave an email and I will send it to you via email.

**Comment by wwsource** [comment]
Hi, my email is 863689877@qq.com

**Comment by danqu130** [comment]
> Hi, my email is [863689877@qq.com](mailto:863689877@qq.com)

I have already sent it. If there are no further questions, I will close this issue in a week.

**Comment by JamesYang110043** [comment]
@danqu130 I hope this message finds you well. I'm a researcher interested in your work on the **FlyChair2 dataset**. The event simulator code you used to create the dataset would be very helpful for my current project.

Would you be willing to share the code? It would be used strictly for research purposes. Thank you for your consideration!
My email : jamesyang@islab.tw

**Comment by AesthetiC631** [comment]
Thank you for your excellent work . I’m writing to ask if you could share the event simulation code. I’d like to use it for academic research only.
Thank you for your time and consideration.
My email:  1554339463@qq.com
