### ISSUE TITLE
Code about visualizing flow

### ISSUE THREAD

**Issue by Hazeliii** [danqu130/DCEIFlow#2]
Thanks for your release. 
But how can I get the flow images like those in your paper? I did't find the code to visualize the flow. I've implemented the code by myself, but I can't get the same results.  It would be very helpful if you can send me the code. My email is 970080465@qq.com. Thanks a lot.

**Comment by danqu130** [comment]
All visualizations of optical flow in the paper are consistent with RAFT (https://github.com/princeton-vl/RAFT/blob/master/core/utils/flow_viz.py). 
This is different from most previous event-based flow estimation methods. However, in line with a CVPR 2020 paper, ``Single image optical flow estimation with an event camera"", which also uses single image and events. In addition, we also need to compare with the image-based methods, so we take the more widely used visualization pipeline consistent with RAFT.

I'm not sure if you've tried it, so please follow up if you still have questions.
