### ISSUE TITLE
Can you also share the event simulation code to me, please?

### ISSUE THREAD

**Issue by Yan98** [danqu130/DCEIFlow#3]
Can you also share the event simulation code to me (u6169130@anu.edu.au), please?

**Comment by danqu130** [comment]
I have already sent it, please use it for academic purposes only. If there are no further questions, I will close this issue in a week.

In order to avoid unnecessary misunderstanding of rights, we do not plan to provide simulated event data. 
If anyone needs the code of event simulation, please leave an email and I will send it to you via email.

**Comment by XMU-qcj** [comment]
Thanks for your work! I hope you can share it with me too, my email is 23020211153904@stu.xmu.edu.cn

> I have already sent it, please use it for academic purposes only. If there are no further questions, I will close this issue in a week.
> 
> In order to avoid unnecessary misunderstanding of rights, we do not plan to provide simulated event data. If anyone needs the code of event simulation, please leave an email and I will send it to you via email.

**Comment by danqu130** [comment]
> Thanks for your work! I hope you can share it with me too, my email is [23020211153904@stu.xmu.edu.cn](mailto:23020211153904@stu.xmu.edu.cn)
> 
> > I have already sent it, please use it for academic purposes only. If there are no further questions, I will close this issue in a week.
> > In order to avoid unnecessary misunderstanding of rights, we do not plan to provide simulated event data. If anyone needs the code of event simulation, please leave an email and I will send it to you via email.

I have already sent it, please use it for academic purposes only. @Unknownnnnnnn

**Comment by parkseobin** [comment]
Thank you for your interesting work and contribution to the research community. Could you also share the code with me too? My email address is seobinpark@utexas.edu

**Comment by danqu130** [comment]
> Thank you for your interesting work and contribution to the research community. Could you also share the code with me too? My email address is [seobinpark@utexas.edu](mailto:seobinpark@utexas.edu)

I have already sent it, please use it for academic purposes only. @parkseobin

**Comment by JamesYang110043** [comment]
@danqu130 
Hi, thank you for your contribution on event-based optical flow.
And can you share the event simulation code with me?
thank you very much. 
My Email : jamesyang@islab.tw

**Comment by danqu130** [comment]
> @danqu130 Hi, thank you for your contribution on event-based optical flow. And can you share the event simulation code with me? thank you very much. My Email : [jamesyang@islab.tw](mailto:jamesyang@islab.tw)

I have already sent it, please use it for academic purposes only.

**Comment by czgst** [comment]
@danqu130 
Thank you for your work and I'm very interested in it! Can you share the event simulation code with me too?
My email address is: 22232051@zju.edu.cn

**Comment by zhenglongyu** [comment]
Thank you for your work! Can you share the event simulation code with me too?
My email address is: zhenglongkon@126.com

**Comment by danqu130** [comment]
I have already sent it, please use for academic purposes only. @czgst @zhenglongyu

**Comment by wwj-xiaohao** [comment]
Thank you for your excellent work and contribution to the research community. Could you share the event simulation code with me too? I will use it for academic purposes only. my email is wuwj53@mail2.sysu.edu.cn. Thank you very much.

**Comment by AesthetiC631** [comment]
Hello,

Thank you for your excellent work on the FlyChair2 dataset. I’m writing to ask if you could share the event simulation code used to create it. I’d like to use it for academic research only.

My email: aesthetic631@163.com
