### ISSUE TITLE
Outcomes of E-RAFT in Table II

### ISSUE THREAD

**Issue by ZPJ-LEFT** [danqu130/DCEIFlow#6]
Hello!
I have some questions about the outcomes of E-RAFT trained on DSEC in Table II:
1. Which weight is used? The one published by E-RAFT or the one trained by yourself?
2. How is the MVSEC data processed? Is it the same as E-RAFT, or did you make some changes?
3. Did you use the warm start mentioned in ERAFT during testing?

I am looking forward to your reply! And I would greatly appreciate it if you could share your testing code on ERAFT.

**Comment by danqu130** [comment]
1. We used the pre-trained model on DSEC (dsec.tar) from E-RAFT repository.
2. To ensure a fair comparison, we split the MVSEC dataset in the same manner as the code of our paper (https://github.com/danqu130/DCEIFlow/blob/master/utils/datasets/MVSEC.py#L55), which is different from E-RAFT.
3. We do not turn on warm start. Warm start can slightly improve performance, but the comparison conclusion will not change. For a fair comparison (none of other methods use more temporal data), we only put the unturned ones in the table.

**Comment by ZPJ-LEFT** [comment]
Thanks for your help!
