### ISSUE TITLE
Question about evaluation dataset

### ISSUE THREAD

**Issue by JamesYang110043** [danqu130/DCEIFlow#7]
Hi, @danqu130 

Firstly, I want to commend you on the excellent work you've done. I have a question regarding the evaluation dataset.
Why did your published work DCEIFlow evaluate on the MVSEC dataset but not on the DSEC dataset in the experiments? What is the reason for this?

Thanks in advance.

**Comment by danqu130** [comment]
Because DSEC published the optical flow leaderboard not long before our paper was submitted. The reviewers did not ask us to add this.
